### ISSUE TITLE
Sửa lỗi

### ISSUE THREAD

**Issue by ttrungn** [QzUzAzN/KitStemHub-Dashboard#23]
- Manager:
 Finished: Chưa có quản lí tài khoản người dùng
- Staff:
Finished: Chưa có tìm kiếm order theo status chờ xác nhận và customer-email
Finished: Phải cho staff xem được phương thức liên hệ với khách hàng để hỗ trợ

**Comment by LMKhoa123** [comment]
Fixed: Chưa có tìm kiếm order theo status chờ xác nhận và customer-email

**Comment by LMKhoa123** [comment]
Fixed: Phải cho staff xem được phương thức liên hệ với khách hàng để hỗ trợ

**Comment by LMKhoa123** [comment]
Fixed: Phải cho staff xem được phương thức liên hệ với khách hàng để hỗ trợ

**Comment by ttrungn** [comment]
> Fixed: Chưa có tìm kiếm order theo status chờ xác nhận và customer-email

Chưa được nha ông ơi, tìm kiếm mình dùng API nha, tìm kiếm trên front-end dữ liệu nó k có chuẩn đâu

**Comment by hquan55252** [comment]
đã fixed :Chưa có quản lí tài khoản người dùng
